majorproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userinterface.urls', namespace="fileApp")),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Plagiarism Detector"
admin.site.site_title = "Plagiarism Detector"
admin.site.index_title = "Welcome to the Admin Area !!"

userinterface/urls.py
from django.urls import path
from . import views

app_name = "fileApp"

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contact/', views.contact, name='contact'),
    path('result/', views.send_file, name = 'result'),
    path('logout/', views.logout, name='logout'),
]

userinterface/models.py
from django.db import models

# Create your models here.
class reviewcontact(models.Model):
    first = models.CharField(max_length=255)
    last = models.CharField(max_length=255)
    email = models.EmailField(max_length=254)
    description = models.TextField()

    def __str__(self):
        return '%s %s' % (self.first, self.last)


class myuploadfile(models.Model):
    fName = models.CharField(max_length=255)
    myFile = models.FileField(upload_to="")

    def __str__(self):
        return self.fName
    

userinterface/views.py
from __future__ import absolute_import
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, auth
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from program import main

from . models import myuploadfile, reviewcontact

# Create your views here.

@login_required(login_url='/login/')
def index(request):
    return render(request, 'index.html')


def home(request):
    return render(request, 'index.html')


def login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:

            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                print("Login successful")
                return redirect("/")
            else:
                print('Username or Password is Incorrect')
                messages.error(request, 'Roll Number or Password is Incorrect')
                return redirect("/login/")
        else:
            print('Fill out all fields')
            messages.error(request, 'Fill out all the fields')
    else:
        return render(request,'login.html')


def signup(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        firstname=request.POST.get('firstname')
        lastname=request.POST.get('lastname')
        phoneNo=request.POST.get('phoneNo')
        email=request.POST.get('email')
        password=request.POST.get('password')

        if User.objects.filter(username=username).exists():
            print("Enter correct roll")
            messages.error(request, 'Account already created')
            return redirect("/signup/")
        elif User.objects.filter(email=email).exists():
            print("Email already exits")
            messages.error(request, 'Email already exits')
            return redirect("/signup/")
        else:        
            myuser = User.objects.create_user(username=username,first_name = firstname,last_name = lastname,password=password,email=email)
            myuser.save()
            print('Your account has been created successfull!!')
            return redirect('/login/')    
    else:
        return render(request, 'signup.html')

def logout(request):
    auth.logout(request)
    return redirect('/')


def aboutus(request):
    return render(request, 'aboutUs.html')

def contact(request):
    if request.method == 'POST':
        first = request.POST.get('firstname')
        last = request.POST.get('lastname')
        description = request.POST.get('description')
        email = request.POST.get('email')
        reviewcontact(first=first,last=last,email=email,description=description).save()
        messages.success(request, 'Your review submitted successfully')
        return redirect('/contact/')
    else:
        return render(request, 'contact.html')



r={}
def send_file(request):
    if request.method == "POST":
        name = request.POST.get("filename")
        myfile = request.FILES.get("uploadfiles")
        myuploadfile(fName=name, myFile=myfile).save()
        
        queryset = myuploadfile.objects.all()
        #print(queryset)
        file=[]
        name=[]
        for obj in queryset:
            name.append(obj.fName)
            file.append(str(obj.myFile).lower())

        file.sort()
        name.sort()

        r=main(myfile)
        #print(data_queryset)
        plag=[]
        for i in range(len(r)):
            plag.append(r["data"+str(i)]["value"])

        #print(plag)
        string=""
        data_queryset={}
        for i in range(len(queryset)):
            if plag[i] >=99:
                dub= "Dublicated document submitted"
            elif plag[i]<=40:
                string="Submission successful"
            else:
                string="Submission failed!! Highly plagiarized"
            data_queryset["data"+str(i)]={"name":name[i],"file":file[i],"value":plag[i]}

        #print(data_queryset)



        res=dict(sorted(data_queryset.items(),key = lambda x: x[1]['value'], reverse=True))
        print(res)
        
        data={
            "data_list" : res
        }


        return render(request, 'result.html', data)

#        return HttpResponse("Uploaded!!")


#    return HttpResponse("Hello, world. You're at the  UI.")

templates/aboutUs.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div id="aboutUsBody">
<h2 style="text-align:center">Our Team</h2>
<div class="row">
  <div class="column">
    <div class="aboutUscard">
      <img src="./../static/images/anish.jpg" alt="Jane" style="height: 200px; width: 200px; border-radius: 100%;">
      <div class="AboutUsContainer">
        <h2>Anish Banjara</h2>
        <p class="title">PUR074BCT004</p>
        <p></p>
        <p>anish074bct004@ioepc.edu.np</p>
        <p><a href = "mailto: anish074bct004@ioepc.edu.np" style="text-decoration: none; color: white;"><button class="button">Contact</button></a></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="aboutUscard">
      <img src="./../static/images/kewal.jpg" alt="Mike" style="height: 200px; width: 200px; border-radius: 100%;">
      <div class="AboutUsContainer">
        <h2>Kewal Singh Myangbo</h2>
        <p class="title">PUR074BCT014</p>
        <p></p>
        <p>kewal074bct014@ioepc.edu.np</p>
        <p><a href = "mailto: kewal074bct014@ioepc.edu.np" style="text-decoration: none; color: white;"><button class="button">Contact</button></a></p>
      </div>
    </div>
  </div>
  
  <div class="column">
    <div class="aboutUscard">
      <img src="./../static/images/pankaj.jpg" alt="John" style="height: 200px; width: 200px; border-radius: 100%;">
      <div class="AboutUsContainer">
        <h2>Pankaj Kumar Soni</h2>
        <p class="title">PUR074BCT019</p>
        <p></p>
        <p>pankaj074bct019@ioepc.edu.np</p>
        <p><a href = "mailto: pankaj074bct019@ioepc.edu.np" style="text-decoration: none; color: white;"><button class="button">Contact</button></a></p>
      </div>
    </div>
  </div>
  
  
  <div class="column">
    <div class="aboutUscard">
      <img src="./../static/images/raj.jpg" alt="John" style="height: 200px; width: 200px; border-radius: 100%;">
      <div class="AboutUsContainer">
        <h2>Raj Kumar Sah</h2>
        <p class="title">PUR074BCT026</p>
        <p></p>
        <p>raj074bct026@ioepc.edu.np</p>
        <p><a href = "mailto: raj074bct026@ioepc.edu.np" style="text-decoration: none; color: white;"><button class="button">Contact</button></a></p>
      </div>
    </div>
  </div>
</div>

</div>
{% endblock %}

templates/contact.html
{% extends 'layout.html' %}

{% block content %}
<div id="aboutUsBody">
  <div class="container">
    <div class="signInContent">
    <div>
      {% for message in messages %}
      <h3><center style="padding:8px; box-shadow: rgba(0, 0, 0, 0.15) 0px 2px 8px; color: green;"> {{message}} </center></h3>
      {% endfor %}
    </div>
    <form action="" method="post" id="signInForm">
      {% csrf_token %}
      <div class="signInTitle">Contact Us!</div>
      <label for="firstname">First name:</label>
      <input type="text" name="firstname" id="firstname" class="signIn">
      <label for="lastname">Last name:</label>
      <input type="text" name="lastname" id="lastname" class="signIn"> 
      <label for="email">Email:</label>
      <input type="text" name="email" id="email" class="signIn"> 
      <label for="text">Description:</label>
      <input type="text" name="description" id="signInPassword" class="signIn"> 
      <button class="signInButton">Submit</button> 
    </form>
  </div>
  </div>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}

<div class="container">  
  <form action = "{% url 'fileApp:result' %}" method = "POST" enctype = "multipart/form-data">
    {% csrf_token %}
    <div id="textLogo">Plagiarism<i style="color: black">-</i>Detector</div>
    <input type = "text" name = "filename" placeholder = "Enter your file name" id="projectname">
    <input type = "file" name = "uploadfiles" id="file-input">
    <button class="uploadBtn">Submit document</button>
  </form>
</div>

{% endblock content %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href= {% static 'index.css' %} >
    <link rel="stylesheet" href= {% static 'login.css' %} >
    <link rel="stylesheet" href= {% static 'result.css' %}>
    <link rel="stylesheet" href= {% static 'aboutUs.css' %}>
    
</head>

<body>
      <div class="navbar">
        <div class="navbarItem left"><a href="/">Home</a></div>
        <div class="navbarItem left"><a href="#">News</a></div>
        <div class="navbarItem left"><a href="/contact/">Contact</a></div>
        <div class="navbarItem left"><a href="/aboutus/">About</a></div> 
        {% if user.is_authenticated %}
          <div class="navbarItem right"><a href="/logout/">Logout</a></div>
          <div class="navbarItem right">Hello, {{user.first_name}} </div>
        {% else %}
          <div class="navbarItem right"><a href="/signup/">Sign Up</a></div>
          <div class="navbarItem right"><a href="/login/">Log in</a></div>
        {% endif %}
      </div>
      
      {% block content %}
      


      {% endblock content %}

      <footer>
        <div>
          Copyright@2078 || Plagiarism Detector
        </div>
      </footer>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div id="aboutUsBody">
  <div class="container">
    
      <div class="signinContent">
        <div>
          {% for message in messages %}
          <h3><center style="padding:8px; box-shadow: rgba(0, 0, 0, 0.5) 0px 2px 8px; color: red;"> {{message}} </center></h3>
          {% endfor %}
        </div>
        <form action="" method="post" id= "signinForm">
          {% csrf_token %}
          <div class="logInTitle">Have a account! Log in.</div>
          <label for="username">Roll Number:</label>
          <input type="text" name="username" id="username" class="loginInput username">
          <label for="password">Password:</label>
          <input type="password" name="password" id="logInPassword" class="loginInput password">
          <button class="loginButton" style="margin-bottom: 8px;">Log In</button>  
        </form>
      <center id="registerCenter">Don't have an account?<a href="/signup/" id="register" style="text-decoration: none; color: green; padding: 4px;">Register</a></center>
      </div>
  </div>
</div>

{% endblock %}

templates/result.html
{% extends 'layout.html' %}

{% block content %}


<center>       
    <div id="cards">
        
        {% for k,v in data_list.items %}
          
            {% if v.value < 99 %}
                <!--{% if v.value < 40 %}
                <h3>Submission Successful</h3>
                {% else %}
                <h3>Submission Failed!! Highly plagarized</h3>
                {% endif %}-->
                <div class="expenses">
                    <h2 class="resultH2"> {{v.name}}</h2>
                    <div class="expense-item__description">
                        <div class="expense-item__price">{{v.value}}% plagarized</div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</center>
    <div id="result1">
    <button><a href = '/'> Goto Home Page</a></button> 
    </div>
    
{% endblock content %}

templates/signup.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div id="aboutUsBody" >
<div class="container">
  <div class="signInContent">
    <div>
      {% for message in messages %}
      <h3><center style="padding:8px; box-shadow: rgba(0, 0, 0, 0.15) 0px 2px 8px; color: red;"> {{message}} </center></h3>
      {% endfor %}
    </div>
    <form action=""  method="post" id="signInForm">
      {% csrf_token %}
      <div class="signInTitle">Create a new account.</div>
      <label for="username">Roll Number:</label>
      <input type="text" name="username" id="username" class="signIn">
      <label for="firstname">First name:</label>
      <input type="text" name="firstname" id="firstname" class="signIn">
      <label for="lastname">Last name:</label>
      <input type="text" name="lastname" id="lastname" class="signIn"> 
      <label for="email">Email:</label>
      <input type="text" name="email" id="email" class="signIn"> 
      <label for="password">Password:</label>
      <input type="password" name="password" id="signInPassword" class="signIn"> 
      <button type = "submit" class="signInButton" style="margin-bottom: 25px">Create an account</button> 
    </form>
  </div>
</div>
</div>
{% endblock %}